function [Time,TrackerO1,TrackerO2,TrackerO3,TrackerX1,TrackerX2,TrackerX3,TrackerY1,TrackerY2,TrackerY3,Tracker11,Tracker12,Tracker13,Tracker21,Tracker22,Tracker23,Tracker1,Tracker2,Tracker3,Tracker4,Tracker5,Tracker6,Tracker7] = importfile_vicon(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,TRACKERO1,TRACKERO2,TRACKERO3,TRACKERX1,TRACKERX2,TRACKERX3,TRACKERY1,TRACKERY2,TRACKERY3,TRACKER11,TRACKER12,TRACKER13,TRACKER21,TRACKER22,TRACKER23,TRACKER1,TRACKER2,TRACKER3,TRACKER4,TRACKER5,TRACKER6,TRACKER7]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME,TRACKERO1,TRACKERO2,TRACKERO3,TRACKERX1,TRACKERX2,TRACKERX3,TRACKERY1,TRACKERY2,TRACKERY3,TRACKER11,TRACKER12,TRACKER13,TRACKER21,TRACKER22,TRACKER23,TRACKER1,TRACKER2,TRACKER3,TRACKER4,TRACKER5,TRACKER6,TRACKER7]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Time,TrackerO1,TrackerO2,TrackerO3,TrackerX1,TrackerX2,TrackerX3,TrackerY1,TrackerY2,TrackerY3,Tracker11,Tracker12,Tracker13,Tracker21,Tracker22,Tracker23,Tracker1,Tracker2,Tracker3,Tracker4,Tracker5,Tracker6,Tracker7] = importfile('ViconTranslate.txt',3, 3705);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2017/08/19 15:09:54

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Format for each line of text:
%   column1: text (%s)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
textscan(fileID, '%[^\n\r]', startRow(1)-1, 'WhiteSpace', '', 'ReturnOnError', false);
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    textscan(fileID, '%[^\n\r]', startRow(block)-1, 'WhiteSpace', '', 'ReturnOnError', false);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Time = dataArray{:, 1};
TrackerO1 = dataArray{:, 2};
TrackerO2 = dataArray{:, 3};
TrackerO3 = dataArray{:, 4};
TrackerX1 = dataArray{:, 5};
TrackerX2 = dataArray{:, 6};
TrackerX3 = dataArray{:, 7};
TrackerY1 = dataArray{:, 8};
TrackerY2 = dataArray{:, 9};
TrackerY3 = dataArray{:, 10};
Tracker11 = dataArray{:, 11};
Tracker12 = dataArray{:, 12};
Tracker13 = dataArray{:, 13};
Tracker21 = dataArray{:, 14};
Tracker22 = dataArray{:, 15};
Tracker23 = dataArray{:, 16};
Tracker1 = dataArray{:, 17};
Tracker2 = dataArray{:, 18};
Tracker3 = dataArray{:, 19};
Tracker4 = dataArray{:, 20};
Tracker5 = dataArray{:, 21};
Tracker6 = dataArray{:, 22};
Tracker7 = dataArray{:, 23};


